#
# .zshenv Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# This file is sourced by all instances of Zsh, and thus, it should be kept as
# small as possible and should only define environment variables.
#
# The configuration files are read in the following order:
#
# /etc/zshenv
#~/.zshenv
#/etc/zprofile
#~/.zprofile
#/etc/zshrc
#~/.zshrc
#~/.zpreztorc
#/etc/zlogin
#~/.zlogin
#~/.zlogout
#/etc/zlogout

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# General path settings
export PATH="/Users/rcogley/gocode:/Users/rcogley/gocode/bin:/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"
export MANPAGER="nvim -c 'set ft=man' -"

# Python
# brew says not needed export PATH=/usr/local/share/python:$PATh
export PYTHONPATH=/usr/local/lib/python2.7:/usr/local/lib/python3.5:$PYTHONPATH

# Golang
export GOPATH=/Users/rcogley/gocode

# Homebrew suggested
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
export HOMEBREW_GITHUB_API_TOKEN="$(cat ~/.homebrew_github_api_token)"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# PROdb API
export PRODB15331TOKEN2411="$(cat ~/.ssh/tokens/PRODB15331TOKEN2411)"


# Zsh
export HELPDIR=/usr/local/share/zsh/help
export REPORTTIME=1

# Onivim2
export ONI2_CONFIG_DIR=/Users/rcogley/.config/oni2/
